In [1]:
import pandas as pd

df = pd.read_csv(
    "../data/recommendations.csv"
)

df.head()

,Hair Color,Eye Color,Skin Tone,Under Tone,Torso length,Body Proportion,Recommended Clothing Colors,Avoid Clothing Colors,Recommended Fitting Style,Recommended Materials,Recommended Patterns,Recommended Jewelry Metal,Recommended Shoes,Recommended Clothing Color Wheel Region,Avoid Clothing Color Wheel Region,Fabric Nature,Don't Exaggerate,Do Exaggerate
0,Black,Brown,Very Fair,Warm,Short Torso,Rectangle,"Earth Tones, Olive, Coral, Peach, Mustard, War...","Cool Blue, Icy Gray, Jewel Tones",Defined Waist,Structured Cotton,Curved Lines,Gold,Low Heels or Flats,"Warm colors (red, orange, yellow, warm greens)",Opposite on color wheel,Firm,Don't exaggerate straight lines,Exaggerate waistline
1,Black,Brown,Very Fair,Warm,Short Torso,Inverted Triangle,"Earth Tones, Olive, Coral, Peach, Mustard, War...","Cool Blue, Icy Gray, Jewel Tones",A-Line Bottoms,Flowy Fabric,Vertical Stripes,Gold,Low Heels or Flats,"Warm colors (red, orange, yellow, warm greens)",Opposite on color wheel,Flowy,Don't exaggerate shoulders,Exaggerate hips
2,Black,Brown,Very Fair,Warm,Short Torso,Triangle,"Earth Tones, Olive, Coral, Peach, Mustard, War...","Cool Blue, Icy Gray, Jewel Tones",Emphasize Top,Lightweight Cotton,Bright Tops,Gold,Low Heels or Flats,"Warm colors (red, orange, yellow, warm greens)",Opposite on color wheel,Light,Don't exaggerate hips,Exaggerate upper body
3,Black,Brown,Very Fair,Warm,Short Torso,Oval,"Earth Tones, Olive, Coral, Peach, Mustard, War...","Cool Blue, Icy Gray, Jewel Tones",Wraps and Empire,"Jersey, Knits",Diagonal Lines,Gold,Low Heels or Flats,"Warm colors (red, orange, yellow, warm greens)",Opposite on color wheel,Stretchy,Don't exaggerate midsection,Exaggerate neckline and legs
4,Black,Brown,Very Fair,Warm,Short Torso,Trapezoid,"Earth Tones, Olive, Coral, Peach, Mustard, War...","Cool Blue, Icy Gray, Jewel Tones",Balanced Fit,Soft Blends,Simple Solids,Gold,Low Heels or Flats,"Warm colors (red, orange, yellow, warm greens)",Opposite on color wheel,Soft,Don't exaggerate any feature,Balance upper and lower body

In [2]:
print(df.columns)

print(df.shape)

Index(['Hair Color', 'Eye Color', 'Skin Tone', 'Under Tone', 'Torso length',
       'Body Proportion', 'Recommended Clothing Colors',
       'Avoid Clothing Colors', 'Recommended Fitting Style',
       'Recommended Materials', 'Recommended Patterns',
       'Recommended Jewelry Metal', 'Recommended Shoes',
       'Recommended Clothing Color Wheel Region',
       'Avoid Clothing Color Wheel Region', 'Fabric Nature',
       'Don't Exaggerate', 'Do Exaggerate'],
      dtype='object')
(15120, 18)

In [3]:
selected_df = df[
    [
        "Hair Color",
        "Eye Color",
        "Skin Tone",
        "Under Tone",
        "Torso length",
        "Body Proportion",
        "Recommended Clothing Colors",
        "Avoid Clothing Colors",
        "Recommended Fitting Style",
        "Recommended Materials",
        "Recommended Patterns",
        "Recommended Jewelry Metal",
        "Recommended Shoes",
        "Recommended Clothing Color Wheel Region"
    ]
]

selected_df.isnull().sum()

Hair Color                                 0
Eye Color                                  0
Skin Tone                                  0
Under Tone                                 0
Torso length                               0
Body Proportion                            0
Recommended Clothing Colors                0
Avoid Clothing Colors                      0
Recommended Fitting Style                  0
Recommended Materials                      0
Recommended Patterns                       0
Recommended Jewelry Metal                  0
Recommended Shoes                          0
Recommended Clothing Color Wheel Region    0
dtype: int64

In [4]:
selected_df = df[
    [
        "Hair Color",
        "Eye Color",
        "Skin Tone",
        "Under Tone",
        "Torso length",
        "Body Proportion",
        "Recommended Clothing Colors",
        "Avoid Clothing Colors",
        "Recommended Fitting Style",
        "Recommended Materials",
        "Recommended Patterns",
        "Recommended Jewelry Metal",
        "Recommended Shoes",
        "Recommended Clothing Color Wheel Region"
    ]
]

selected_df.to_csv(
    "../data/stylist_dataset.csv",
    index=False
)

print(selected_df.shape)

(15120, 14)

In [5]:
X = selected_df[
    [
        "Hair Color",
        "Eye Color",
        "Skin Tone",
        "Under Tone",
        "Torso length",
        "Body Proportion"
    ]
]

y = selected_df[
    [
        "Recommended Clothing Colors",
        "Avoid Clothing Colors",
        "Recommended Fitting Style",
        "Recommended Materials",
        "Recommended Patterns",
        "Recommended Jewelry Metal",
        "Recommended Shoes",
        "Recommended Clothing Color Wheel Region"
    ]
]

print(X.head())

print(y.head())

  Hair Color Eye Color  Skin Tone Under Tone Torso length    Body Proportion
0      Black     Brown  Very Fair       Warm  Short Torso          Rectangle
1      Black     Brown  Very Fair       Warm  Short Torso  Inverted Triangle
2      Black     Brown  Very Fair       Warm  Short Torso           Triangle
3      Black     Brown  Very Fair       Warm  Short Torso               Oval
4      Black     Brown  Very Fair       Warm  Short Torso          Trapezoid
                         Recommended Clothing Colors  \
0  Earth Tones, Olive, Coral, Peach, Mustard, War...
1  Earth Tones, Olive, Coral, Peach, Mustard, War...
2  Earth Tones, Olive, Coral, Peach, Mustard, War...
3  Earth Tones, Olive, Coral, Peach, Mustard, War...
4  Earth Tones, Olive, Coral, Peach, Mustard, War...

              Avoid Clothing Colors Recommended Fitting Style  \
0  Cool Blue, Icy Gray, Jewel Tones             Defined Waist
1  Cool Blue, Icy Gray, Jewel Tones            A-Line Bottoms
2  Cool Blue, Icy Gray, Jewel Tones             Emphasize Top
3  Cool Blue, Icy Gray, Jewel Tones          Wraps and Empire
4  Cool Blue, Icy Gray, Jewel Tones              Balanced Fit

  Recommended Materials Recommended Patterns Recommended Jewelry Metal  \
0     Structured Cotton         Curved Lines                      Gold
1          Flowy Fabric     Vertical Stripes                      Gold
2    Lightweight Cotton          Bright Tops                      Gold
3         Jersey, Knits       Diagonal Lines                      Gold
4           Soft Blends        Simple Solids                      Gold

    Recommended Shoes         Recommended Clothing Color Wheel Region
0  Low Heels or Flats  Warm colors (red, orange, yellow, warm greens)
1  Low Heels or Flats  Warm colors (red, orange, yellow, warm greens)
2  Low Heels or Flats  Warm colors (red, orange, yellow, warm greens)
3  Low Heels or Flats  Warm colors (red, orange, yellow, warm greens)
4  Low Heels or Flats  Warm colors (red, orange, yellow, warm greens)

In [6]:
from sklearn.preprocessing import LabelEncoder

encoders = {}

X_encoded = X.copy()

for column in X.columns:

    le = LabelEncoder()

    X_encoded[column] = le.fit_transform(
        X[column]
    )

    encoders[column] = le

X_encoded.head()

   Hair Color  Eye Color  Skin Tone  Under Tone  Torso length  Body Proportion
0           0          2          5           2             2                4
1           0          2          5           2             2                2
2           0          2          5           2             2                6
3           0          2          5           2             2                3
4           0          2          5           2             2                5

In [7]:
y_encoded = y.copy()

target_encoders = {}

for column in y.columns:

    le = LabelEncoder()

    y_encoded[column] = le.fit_transform(
        y[column]
    )

    target_encoders[column] = le

y_encoded.head()

,Recommended Clothing Colors,Avoid Clothing Colors,Recommended Fitting Style,Recommended Materials,Recommended Patterns,Recommended Jewelry Metal,Recommended Shoes,Recommended Clothing Color Wheel Region
0,0,0,2,6,1,0,2,2
1,0,0,0,1,6,0,2,2
2,0,0,3,3,0,0,2,2
3,0,0,6,2,3,0,2,2
4,0,0,1,4,4,0,2,2

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y_encoded,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)

print(X_test.shape)

print(y_train.shape)

print(y_test.shape)

(12096, 6)
(3024, 6)
(12096, 8)
(3024, 8)

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier

model = MultiOutputClassifier(
    RandomForestClassifier(
        n_estimators=100,
        random_state=42
    )
)

model.fit(
    X_train,
    y_train
)

print("Training complete")

Training complete

In [10]:
sample = X_test.iloc[[0]]

prediction = model.predict(sample)

prediction

array([[1, 2, 0, 1, 6, 2, 1, 0]])

In [11]:
decoded_output = {}

for i, column in enumerate(y.columns):

    decoded_output[column] = target_encoders[
        column
    ].inverse_transform(
        [prediction[0][i]]
    )[0]

decoded_output

{'Recommended Clothing Colors': 'Jewel Tones, Icy Blue, Lavender, Silver, Emerald',
 'Avoid Clothing Colors': 'Orange, Mustard, Brown',
 'Recommended Fitting Style': 'A-Line Bottoms',
 'Recommended Materials': 'Flowy Fabric',
 'Recommended Patterns': 'Vertical Stripes',
 'Recommended Jewelry Metal': 'Silver',
 'Recommended Shoes': 'Heels or Platforms',
 'Recommended Clothing Color Wheel Region': 'Cool colors (blue, green, violet, cool grays)'}

In [12]:
from sklearn.metrics import accuracy_score

predictions = model.predict(
    X_test
)

for i, column in enumerate(y.columns):

    acc = accuracy_score(
        y_test.iloc[:, i],
        predictions[:, i]
    )

    print(
        column,
        ":",
        round(acc, 3)
    )

Recommended Clothing Colors : 1.0
Avoid Clothing Colors : 1.0
Recommended Fitting Style : 1.0
Recommended Materials : 1.0
Recommended Patterns : 1.0
Recommended Jewelry Metal : 1.0
Recommended Shoes : 1.0
Recommended Clothing Color Wheel Region : 1.0

In [13]:
for column in y.columns:

    print(
        column,
        ":",
        y[column].nunique()
    )

Recommended Clothing Colors : 3
Avoid Clothing Colors : 3
Recommended Fitting Style : 7
Recommended Materials : 7
Recommended Patterns : 7
Recommended Jewelry Metal : 3
Recommended Shoes : 3
Recommended Clothing Color Wheel Region : 3

In [14]:
import pandas as pd

feature_importance = pd.DataFrame(
    {
        "Feature": X.columns,
        "Importance":
        model.estimators_[0]
        .feature_importances_
    }
)

feature_importance.sort_values(
    by="Importance",
    ascending=False
)

           Feature  Importance
3       Under Tone    0.985643
1        Eye Color    0.003870
5  Body Proportion    0.003392
2        Skin Tone    0.002874
0       Hair Color    0.002715
4     Torso length    0.001506

In [15]:
for column in X.columns:

    print(
        column,
        ":",
        X[column].nunique()
    )

Hair Color : 5
Eye Color : 8
Skin Tone : 6
Under Tone : 3
Torso length : 3
Body Proportion : 7

In [16]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(
    X_encoded
)

kmeans = KMeans(
    n_clusters=5,
    random_state=42
)

clusters = kmeans.fit_predict(
    X_scaled
)

selected_df["Cluster"] = clusters

selected_df[
    [
        "Hair Color",
        "Skin Tone",
        "Under Tone",
        "Cluster"
    ]
].head()

C:\Users\DELL\AppData\Local\Temp\ipykernel_22116\1274455542.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["Cluster"] = clusters

  Hair Color  Skin Tone Under Tone  Cluster
0      Black  Very Fair       Warm        3
1      Black  Very Fair       Warm        3
2      Black  Very Fair       Warm        1
3      Black  Very Fair       Warm        3
4      Black  Very Fair       Warm        1

In [17]:
selected_df = selected_df.copy()

selected_df["Cluster"] = clusters

In [18]:
selected_df.groupby(
    "Cluster"
)[
    [
        "Skin Tone",
        "Under Tone",
        "Recommended Jewelry Metal"
    ]
].agg(
    lambda x: x.mode()[0]
)

         Skin Tone Under Tone Recommended Jewelry Metal
Cluster
0        Very Fair       Cool                    Silver
1        Very Fair       Cool                 Rose Gold
2            Brown       Cool                    Silver
3        Very Dark       Warm                      Gold
4            Brown       Warm                      Gold

In [19]:
def get_cluster_recommendation(
    cluster_id
):

    return selected_df[
        selected_df[
            "Cluster"
        ] == cluster_id
    ][
        [
            "Recommended Clothing Colors",
            "Recommended Jewelry Metal",
            "Recommended Materials",
            "Recommended Shoes"
        ]
    ].mode().iloc[0]


get_cluster_recommendation(
    3
)

Recommended Clothing Colors    Earth Tones, Olive, Coral, Peach, Mustard, War...
Recommended Jewelry Metal                                                   Gold
Recommended Materials                                              Drapey Fabric
Recommended Shoes                                             Heels or Platforms
Name: 0, dtype: object

In [21]:
import joblib

joblib.dump(
    kmeans,
    "../models/kmeans_stylist.pkl"
)

joblib.dump(
    scaler,
    "../models/scaler.pkl"
)

joblib.dump(
    encoders,
    "../models/input_encoders.pkl"
)

joblib.dump(
    selected_df,
    "../models/recommendation_data.pkl"
)

print("Saved")

Saved